"""empty message

Revision ID: 0d1c6e203690
Revises: a5cffa318ac2
Create Date: 2024-09-13 11:55:07.774966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d1c6e203690'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nick_name', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=250), nullable=True))
        batch_op.create_unique_constraint(None, ['nick_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('nick_name')

    # ### end Alembic commands ###
