"""empty message

Revision ID: 0ea5a20ae14f
Revises: 19b46b6fa8e6
Create Date: 2024-09-13 13:03:33.120368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ea5a20ae14f'
down_revision = '19b46b6fa8e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('films',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('episode_num', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.Integer(), nullable=True),
    sa.Column('director', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('films')
    # ### end Alembic commands ###
