"""empty message

Revision ID: 3bed84b5ec46
Revises: 0d1c6e203690
Create Date: 2024-09-13 12:10:10.537059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bed84b5ec46'
down_revision = '0d1c6e203690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('starships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('starship_class', sa.String(length=250), nullable=True),
    sa.Column('manufacturer', sa.String(length=250), nullable=True),
    sa.Column('cost_in_credits', sa.String(length=250), nullable=True),
    sa.Column('length', sa.String(length=250), nullable=True),
    sa.Column('crew', sa.String(length=250), nullable=True),
    sa.Column('passengers', sa.String(length=250), nullable=True),
    sa.Column('max_atmosphering_speed', sa.Integer(), nullable=True),
    sa.Column('hyperdrive_rating', sa.String(length=250), nullable=True),
    sa.Column('MGLT', sa.String(length=250), nullable=True),
    sa.Column('cargo_capacity', sa.String(length=250), nullable=True),
    sa.Column('consumables', sa.String(length=250), nullable=True),
    sa.Column('pilots', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('starships')
    # ### end Alembic commands ###
